openapi: 3.0.2
components:
  schemas:
    answer:
      type: object
      properties:
        id:
          type: integer
          summary: PK
        question_id:
          type: integer
          summary: 'Question id'
        code:
          type: string
          summary: 'Answer code'
        sort_order:
          type: integer
          summary: 'Answer sort order'
        assessment_value:
          type: integer
          summary: ''
        scale_id:
          type: integer
          summary: ''
    answer_l10n:
      type: object
      properties:
        id:
          type: int
          summary: 'Primary key'
        answer_id:
          type: int
          summary: 'Answer Id'
        answer:
          type: string
          summary: 'The answer text'
        language:
          type: string
          summary: 'Language code'
    failed_login_attempt:
      type: object
      properties:
        id:
          type: integer
          summary: ''
        ip:
          type: string
          summary: 'Ip address'
        last_attempt:
          type: string
          summary: ''
        number_attempts:
          type: integer
          summary: ''
    permission:
      type: object
      properties:
        id:
          type: integer
          summary: ''
        entity:
          type: string
          summary: ''
        entity_id:
          type: integer
          summary: ''
        user_id:
          type: integer
          summary: ''
        permission:
          type: string
          summary: ''
        create_perm:
          type: integer
          summary: ''
        read_perm:
          type: integer
          summary: ''
        update_perm:
          type: integer
          summary: ''
        delete_perm:
          type: integer
          summary: ''
        import_perm:
          type: integer
          summary: ''
        export_perm:
          type: integer
          summary: ''
    question:
      type: object
      properties:
        question_id:
          type: integer
          summary: 'Question ID.'
        survey_id:
          type: integer
          summary: 'Survey ID'
        group_id:
          type: integer
          summary: 'QuestionGroup ID where question is displayed'
        type:
          type: string
          summary: ''
        title:
          type: string
          summary: 'Question Code'
        preg:
          type: string
          summary: ''
        question_order:
          type: integer
          summary: 'Question order in greoup'
        parent_question_id:
          type: integer
          summary: 'Questions parent question ID eg for subquestions'
        scale_id:
          type: integer
          summary: 'The scale ID'
        relevance:
          type: string
          summary: 'Questions relevane equation'
        module_name:
          type: string
          summary: ''
        same_script:
          type: integer
          summary: 'Whether the same script should be used for all languages'
    question_attribute:
      type: object
      properties:
        id:
          type: integer
          summary: 'ID Primary key'
        question_id:
          type: integer
          summary: 'Question ID'
        value:
          type: string
          summary: 'Attribute value'
    question_group:
      type: object
      properties:
        id:
          type: integer
          summary: ID
        survey_id:
          type: integer
          summary: 'Survey ID'
        randomization_group:
          type: string
          summary: 'Randomization group'
        survey:
          type: Survey
          summary: ''
    question_group_l10n:
      type: object
      properties:
        id:
          type: integer
        group_id:
          type: integer
        group_name:
          type: string
          summary: 'QuestionGroup display text. The actual question.'
        description:
          type: string
        language:
          type: string
    question_l10n:
      type: object
      properties:
        id:
          type: integer
          summary: 'primary key'
        question_id:
          type: integer
          summary: 'question id'
        question:
          type: string
          summary: 'Question display text. The actual question.'
        help:
          type: string
        script:
          type: string
          summary: 'Question script to be executed on runtime'
        language:
          type: string
    setting_global:
      type: object
      properties:
        name:
          type: string
          summary: 'Setting name'
        value:
          type: string
          summary: 'Setting value'
    survey:
      type: object
      properties:
        id:
          type: integer
          summary: 'Survey ID'
        owner_id:
          type: integer
          summary: ''
        admin_email:
          type: string
          summary: 'Survey administrator email address'
        fax_to:
          type: string
          summary: ''
        template:
          type: string
          summary: 'Template name'
        language:
          type: string
          summary: 'Survey base language'
        auto_number_start:
          type: integer
          summary: ''
        use_captcha:
          type: string
          summary: ''
        use_tokens:
          type: string
          summary: ''
        bounce_email:
          type: string
          summary: 'Bounce email address'
        attribute_descriptions:
          type: string
          summary: ''
        email_notification_to:
          type: string
          summary: 'Email address to send basic admin notification email to'
        bounce_time:
          type: integer
          summary: ''
        bounce_processing:
          type: string
          summary: ''
        bounce_account_type:
          type: string
          summary: ''
        bounce_accounthost:
          type: string
          summary: ''
        bounce_account_password:
          type: string
          summary: ''
        bounce_account_encryption:
          type: string
          summary: ''
        bounce_account_user:
          type: string
          summary: ''
        google_analytics_api_key:
          type: string
          summary: 'Google Analytics Tracking ID'
        token_encryption_options:
          type: string
          summary: 'Token encryption options'
        creation_date:
          type: string
          summary: 'Creation date formatted according to user format'
        start_date:
          type: string
          summary: 'Start date formatted according to user format'
        expiry_date:
          type: string
          summary: 'Expiry date formatted according to user format'
    survey_language_setting:
      type: object
      properties:
        id:
          type: integer
          summary: 'Survey ID'
        title:
          type: string
          summary: 'Survey title in this language'
        description:
          type: string
          summary: 'Survey description in this language'
        date_format:
          type: string
          summary: ''
        attribute_captions:
          type: string
          summary: ''
        attachments:
          type: string
          summary: ''
        survey:
          type: Survey
          summary: ''
        owner:
          type: User
          summary: ''
    survey_group:
      type: object
      properties:
        id:
          type: integer
          summary: ''
        name:
          type: string
          summary: ''
        title:
          type: string
          summary: ''
        description:
          type: string
          summary: ''
        sort_order:
          type: integer
          summary: ''
        owner_id:
          type: integer
          summary: ''
        parent_id:
          type: integer
          summary: ''
        created:
          type: string
          summary: ''
        modified:
          type: string
          summary: ''
        created_by:
          type: integer
          summary: ''
        parent_group:
          type: object
          summary: ''
        has_surveys:
          type: boolean
          summary: ''
    user:
      type: object
      properties:
        users_name:
          type: string
          summary: 'Users username'
        parent_id:
          type: integer
          summary: ''
        validation_key:
          type: string
          summary: 'used for email link to reset or create a password for a survey participant'
        validation_key_expiration:
          type: string
          summary: 'datetime when the validation key expires'
        parent_user:
          type: User
          summary: 'Parent user'
        last_login:
          type: string
          summary: ''
