openapi: 3.0.2
info:
  title: LimeSurvey REST API
  version: 0.1.0-alpha.0
  license:
    name: GPL-2.0
    url: "https://www.gnu.org/licenses/gpl-2.0.html"

paths:
  /surveys:
    get:
      summary: List all surveys
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/survey"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"

    post:
      summary: Create a new survey
      responses:
        "201":
          header:
            Location:
              description: URL of the new survey
              required: true
              schema:
                type: string
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"

  /surveys/{survey_id}:
    get:
      summary: Get a survey
      parameters:
        - $ref: "#/components/parameters/survey_id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/survey"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"
        "404":
          $ref: "#/components/responses/not_found"

    put:
      summary: Updates a survey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/survey"
      parameters:
        - $ref: "#/components/parameters/survey_id"
      responses:
        "204":
          $ref: "#/components/responses/empty_ok"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"
        "404":
          $ref: "#/components/responses/not_found"

    delete:
      summary: Deletes a survey
      parameters:
        - $ref: "#/components/parameters/survey_id"
      responses:
        "204":
          $ref: "#/components/responses/empty_ok"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"
        "404":
          $ref: "#/components/responses/not_found"

  /surveys/{survey_id}/groups:
    get:
      summary: List question groups of the survey
      parameters:
        - $ref: "#/components/parameters/survey_id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  - $ref: "#/components/schemas/question_group"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"

    post:
      summary: Create a new question group in the survey
      parameters:
        - $ref: "#/components/parameters/survey_id"
      responses:
        "201":
          description: Created
          header:
            Location:
              description: URL of the new question group
              required: true
              schema:
                type: string
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"

  /surveys/{survey_id}/groups/{question_group_id}:
    get:
      summary: Get a question group of the survey
      parameters:
        - $ref: "#/components/parameters/survey_id"
        - $ref: "#/components/parameters/question_group_id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/question_group"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"
        "404":
          $ref: "#/components/responses/not_found"

    put:
      summary: Updates a question group of the survey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/question_group"
      parameters:
        - $ref: "#/components/parameters/survey_id"
        - $ref: "#/components/parameters/question_group_id"
      responses:
        "204":
          $ref: "#/components/responses/empty_ok"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"
        "404":
          $ref: "#/components/responses/not_found"

    delete:
      summary: Deletes a question group in the survey
      parameters:
        - $ref: "#/components/parameters/survey_id"
        - $ref: "#/components/parameters/question_group_id"
      responses:
        "204":
          $ref: "#/components/responses/empty_ok"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          $ref: "#/components/responses/permission_denied"
        "404":
          $ref: "#/components/responses/not_found"

components:
  parameters:
    question_group_id:
      name: question_group_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/question_group_id"
    survey_id:
      name: survey_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/survey_id"

  responses:
    empty_ok:
      description: OK
    not_found:
      description: Resource not found
    permission_denied:
      description: Permission denied
    unauthorized:
      description: Unauthorized request

  schemas:
    answer:
      type: object
      properties:
        id:
          type: integer
          description: PK
        question_id:
          type: integer
          description: 'Question id'
        code:
          type: string
          description: 'Answer code'
        sort_order:
          type: integer
          description: 'Answer sort order'
        assessment_value:
          type: integer
          description: ''
        scale_id:
          type: integer
          description: ''
    answer_l10n:
      type: object
      properties:
        id:
          type: integer
          description: 'Primary key'
        answer_id:
          type: integer
          description: 'Answer Id'
        answer:
          type: string
          description: 'The answer text'
        language:
          type: string
          description: 'Language code'
    failed_login_attempt:
      type: object
      properties:
        id:
          type: integer
          description: ''
        ip:
          type: string
          description: 'Ip address'
        last_attempt:
          type: string
          description: ''
        number_attempts:
          type: integer
          description: ''
    permission:
      type: object
      properties:
        id:
          type: integer
          description: ''
        entity:
          type: string
          description: ''
        entity_id:
          type: integer
          description: ''
        user_id:
          type: integer
          description: ''
        permission:
          type: string
          description: ''
        create_perm:
          type: integer
          description: ''
        read_perm:
          type: integer
          description: ''
        update_perm:
          type: integer
          description: ''
        delete_perm:
          type: integer
          description: ''
        import_perm:
          type: integer
          description: ''
        export_perm:
          type: integer
          description: ''
    question:
      type: object
      properties:
        question_id:
          type: integer
          description: 'Question ID.'
        survey_id:
          $ref: "#/components/schemas/survey_id"
        group_id:
          type: integer
          description: 'QuestionGroup ID where question is displayed'
        type:
          type: string
          description: ''
        title:
          type: string
          description: 'Question Code'
        preg:
          type: string
          description: ''
        question_order:
          type: integer
          description: 'Question order in greoup'
        parent_question_id:
          type: integer
          description: 'Questions parent question ID eg for subquestions'
        scale_id:
          type: integer
          description: 'The scale ID'
        relevance:
          type: string
          description: 'Questions relevane equation'
        module_name:
          type: string
          description: ''
        same_script:
          type: integer
          description: 'Whether the same script should be used for all languages'
    question_attribute:
      type: object
      properties:
        id:
          type: integer
          description: 'ID Primary key'
        question_id:
          type: integer
          description: 'Question ID'
        value:
          type: string
          description: 'Attribute value'
    question_group:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/question_group_id"
        survey_id:
          $ref: "#/components/schemas/survey_id"
    question_group_id:
      type: integer
      description: Question group ID
    question_group_l10n:
      type: object
      properties:
        id:
          type: integer
        group_id:
          type: integer
        group_name:
          type: string
          description: 'QuestionGroup display text. The actual question.'
        description:
          type: string
        language:
          type: string
    question_l10n:
      type: object
      properties:
        id:
          type: integer
          description: 'primary key'
        question_id:
          type: integer
          description: 'question id'
        question:
          type: string
          description: 'Question display text. The actual question.'
        help:
          type: string
        script:
          type: string
          description: 'Question script to be executed on runtime'
        language:
          type: string
    setting_global:
      type: object
      properties:
        name:
          type: string
          description: 'Setting name'
        value:
          type: string
          description: 'Setting value'
    survey:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/survey_id"
        owner_id:
          type: integer
        admin_email:
          type: string
          description: 'Survey administrator email address'
        fax_to:
          type: string
          description: ''
        template:
          type: string
          description: 'Template name'
        language:
          type: string
          description: 'Survey base language'
        auto_number_start:
          type: integer
          description: ''
        use_captcha:
          type: string
          description: ''
        use_tokens:
          type: string
          description: ''
        bounce_email:
          type: string
          description: 'Bounce email address'
        attribute_descriptions:
          type: string
          description: ''
        email_notification_to:
          type: string
          description: 'Email address to send basic admin notification email to'
        bounce_time:
          type: integer
          description: ''
        bounce_processing:
          type: string
          description: ''
        bounce_account_type:
          type: string
          description: ''
        bounce_accounthost:
          type: string
          description: ''
        bounce_account_password:
          type: string
          description: ''
        bounce_account_encryption:
          type: string
          description: ''
        bounce_account_user:
          type: string
          description: ''
        google_analytics_api_key:
          type: string
          description: 'Google Analytics Tracking ID'
        token_encryption_options:
          type: string
          description: 'Token encryption options'
        creation_date:
          type: string
          description: 'Creation date formatted according to user format'
        start_date:
          type: string
          description: 'Start date formatted according to user format'
        expiry_date:
          type: string
          description: 'Expiry date formatted according to user format'
    survey_id:
      type: integer
      description: Survey ID
    survey_language_setting:
      type: object
      properties:
        id:
          type: integer
          description: 'Survey ID'
        title:
          type: string
          description: 'Survey title in this language'
        description:
          type: string
          description: 'Survey description in this language'
        date_format:
          type: string
          description: ''
        attribute_captions:
          type: string
          description: ''
        attachments:
          type: string
          description: ''
    survey_group:
      type: object
      properties:
        id:
          type: integer
          description: ''
        name:
          type: string
          description: ''
        title:
          type: string
          description: ''
        description:
          type: string
          description: ''
        sort_order:
          type: integer
          description: ''
        owner_id:
          type: integer
          description: ''
        parent_id:
          type: integer
          description: ''
        created:
          type: string
          description: ''
        modified:
          type: string
          description: ''
        created_by:
          type: integer
          description: ''
        parent_group:
          type: object
          description: ''
        has_surveys:
          type: boolean
          description: ''
    user:
      type: object
      properties:
        users_name:
          type: string
          description: 'Users username'
        parent_id:
          type: integer
          description: ''
        validation_key:
          type: string
          description: 'used for email link to reset or create a password for a survey participant'
        validation_key_expiration:
          type: string
          description: 'datetime when the validation key expires'
        last_login:
          type: string
          description: ''
