openapi: 3.0.2
info:
  title: LimeSurvey REST API
  version: 0.1.0-alpha.5
  license:
    name: GPL-2.0
    url: "https://www.gnu.org/licenses/gpl-2.0.html"

# TODO: Add 409 Conflict to POSTs
# TODO: Support pagination
paths:
  /:
    $ref: "./paths/root.yaml"

  /login/bearer_token:
    $ref: "./paths/login/bearer_token.yaml"

  /surveys:
    $ref: "./paths/surveys.yaml"
  /surveys/{survey_id}:
    $ref: "./paths/surveys_by_id.yaml"
  /surveys/{survey_id}/question_groups:
    $ref: "./paths/surveys/question_groups.yaml"
  /surveys/{survey_id}/question_groups/{question_group_id}:
    $ref: "./paths/surveys/question_groups_by_id.yaml"
  /surveys/{survey_id}/questions:
    $ref: "./paths/surveys/questions.yaml"
  /surveys/{survey_id}/questions/{question_id}:
    $ref: "./paths/surveys/questions_by_id.yaml"
  /surveys/{survey_id}/questions/{question_id}/answers:
    $ref: "./paths/surveys/questions/answers.yaml"
  /surveys/{survey_id}/questions/{question_id}/answers/{answer_id}:
    $ref: "./paths/surveys/questions/answers_by_id.yaml"

  /surveys/{survey_id}/responses:
    $ref: "./paths/surveys/responses.yaml"
  /surveys/{survey_id}/responses/{response_id}:
    $ref: "./paths/surveys/responses_by_id.yaml"

components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer

security:
  # Apply it globally
  - bearer_auth: []
